# Generated by Django 2.2 on 2019-04-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190411_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='no_expediente',
            field=models.IntegerField(unique=True, verbose_name='Número de expediente'),
        ),
    ]
