# Generated by Django 2.2 on 2019-04-11 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190411_0238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allergy',
            old_name='open_date',
            new_name='fecha_alta',
        ),
        migrations.RenameField(
            model_name='allergy',
            old_name='medicine',
            new_name='medicamento',
        ),
        migrations.RenameField(
            model_name='allergy',
            old_name='name',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='allergy',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alergias', to='accounts.Account'),
        ),
    ]
